# Generated by Django 5.2.3 on 2025-06-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_aircraft_flight_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
