# Generated by Django 5.2.3 on 2025-06-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='document',
        ),
    ]
