# Generated by Django 5.2.3 on 2025-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_passenger_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
