# Generated by Django 5.2.3 on 2025-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_seat_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='seat_layout',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='technical_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
