# Generated by Django 5.2.3 on 2025-06-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_aircraft_seat_layout_aircraft_technical_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.passenger'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flights.aircraft'),
        ),
    ]
