# Generated by Django 5.2.3 on 2025-06-17 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_alter_booking_flight_alter_booking_passenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
