# Generated by Django 5.2.3 on 2025-06-17 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rol', models.CharField(default='employee', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seat_number',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='columns',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estado',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='estado',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='tipo_documento',
            field=models.CharField(default='DNI', max_length=50),
        ),
        migrations.AddField(
            model_name='seat',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft'),
        ),
        migrations.AddField(
            model_name='seat',
            name='columna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='fila',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='tipo',
            field=models.CharField(default='economy', max_length=20),
        ),
    ]
